export const GTDStrings = {
  ADD_TOPIC: "Add Topic",
  ADD_NEW_TOPIC: "Add New Topic",
  TOPIC_NAME: "Topic Name",
  ALL_TOPICS: "All Topics",
  ADD_PROJECT: "Add Project",
  ADD_NEXT_ACTIONS: "Add Next Actions",
  ADD_NEXT_ACTION: "Add Next Action",
  ADD_NEXT_ACTION_BTN_TEXT: "Add",
  ADD_NEXT_ACTION_AND_CONTINUE_BTN_TEXT: "Add and Create Another",
  PROJECT_NAME: "Project Name",
  SELECT_TAGS: "Tags",
  SELECT_TOPIC: "Select Topic",
  SELECT_PROJECT: "Select Project",
  NEXT_ACTION_NAME: "Next Action Title",
  NEXT_ACTION_DESCRIPTION: "Description",
  ACTIVATE_PROJECT_TITLE: "Activate Project",
  ACTIVATE_PROJECT_TEXT: (projectName: string) => `Are you sure you want to activate the ${projectName} project?`,
  DEACTIVATE_PROJECT_TEXT: (projectName: string) => `Are you sure you want to deactivate the ${projectName} project?`,
  ACTIVATE_PROJECT: "Activate",
  DEACTIVATE_PROJECT: "Deactivate",
  UPDATE_PROJECT: "Update Project",
  UPDATE_NEXT_ACTION: "Update Next Action",
  COMPLETE_TEXT: (nextActionName: string) => `Are you sure you want to mark ${nextActionName} as complete?`,
  UNDO_COMPLETE_TEXT: (nextActionName: string) => `Are you sure you want to mark ${nextActionName} as not complete?`
};